var list = {
		Genesis:"./books/OT/Genesis.json",
		Exodus:"./books/OT/Exodus.json",
		Leviticus:"./books/OT/Leviticus.json",
		Numbers:"./books/OT/Numbers.json",
		Deuteronomy:"./books/OT/Deuteronomy.json",
		Joshua:"./books/OT/Joshua.json",
		Judges:"./books/OT/Judges.json",
		Ruth:"./books/OT/Ruth.json",
        "1 Samuel":"./books/OT/1 Samuel.json",
		"2 Samuel":"./books/OT/2 Samuel.json",
		"1 Kings":"./books/OT/1 Kings.json",
		"2 Kings":"./books/OT/2 Kings.json",
		Matthew:"./books/NT/Matthew.json",
		Mark:"./books/NT/Mark.json",
		Luke:"./books/NT/Luke.json",
		John:"./books/NT/John.json",
		Acts:"./books/NT/Acts.json",
		Romans:"./books/NT/Romans.json",
		"1 Corinthians":"./books/NT/1 Corinthians.json",
		"2 Corinthians":"./books/NT/2 Corinthians.json",
		Galatians:"./books/NT/Galatians.json",
		Ephesians:"./books/NT/Ephesians.json",
		Philippians:"./books/NT/Philippians.json",
		Colossians:"./books/NT/Colossians.json",
		"1 John":"./books/NT/1 John.json"		
		};